In [1]:
import torch
from torch.utils.data import Dataset, DataLoader

class FactoryDataset(Dataset):
    def __init__(self, x_list, y_list):
        self.x_data = torch.tensor(x_list, dtype=torch.float32)
        self.y_data = torch.tensor(y_list, dtype=torch.long)

    def __len__(self):
        return len(self.x_data)

    def __getitem__(self, idx):
        return self.x_data[idx], self.y_data[idx]


x_list = [[1.2, 0.5], [3.4, 1.2], [0.8, 0.3], [4.1, 1.9]]
y_list = [0, 1, 0, 1]

dataset = FactoryDataset(x_list, y_list)

dataloader = DataLoader(dataset, batch_size=2, shuffle=False)

first_x, first_y = None, None

for batch_idx, (x_batch, y_batch) in enumerate(dataloader):
    print(f"[Batch {batch_idx}]")
    print("x_batch:\n", x_batch)
    print("y_batch:\n", y_batch)
    print("x_batch.shape:", x_batch.shape)
    print("y_batch.shape:", y_batch.shape)
    print("-" * 40)

    
    if batch_idx == 0:
        first_x, first_y = x_batch, y_batch

print("첫 번째 배치 x shape:", first_x.shape)
print("첫 번째 배치 y shape:", first_y.shape)

[Batch 0]
x_batch:
 tensor([[1.2000, 0.5000],
        [3.4000, 1.2000]])
y_batch:
 tensor([0, 1])
x_batch.shape: torch.Size([2, 2])
y_batch.shape: torch.Size([2])
----------------------------------------
[Batch 1]
x_batch:
 tensor([[0.8000, 0.3000],
        [4.1000, 1.9000]])
y_batch:
 tensor([0, 1])
x_batch.shape: torch.Size([2, 2])
y_batch.shape: torch.Size([2])
----------------------------------------
첫 번째 배치 x shape: torch.Size([2, 2])
첫 번째 배치 y shape: torch.Size([2])
